### ISSUE TITLE
"untrusted notebook pycon-pandas-tutorial/Exercises-1.ipynb"

### ISSUE THREAD

**Issue by dbl001** [brandon-rhodes/pycon-pandas-tutorial#5]
Hi,

The Exercises-1.ipynb notebook can't connect to the Notebook server.
Any ideas?

David-Laxers-MacBook-Pro:~ davidlaxer$ ipython notebook --profile=nbserver
[I 19:08:00.252 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
[I 19:08:00.317 NotebookApp] Serving notebooks from local directory: /Users/davidlaxer
[I 19:08:00.317 NotebookApp] 0 active kernels 
[I 19:08:00.317 NotebookApp] The IPython Notebook is running at: https://127.0.0.1:9999/
[I 19:08:00.317 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 19:08:25.637 NotebookApp] Writing notebook-signing key to /Users/davidlaxer/.ipython/profile_nbserver/security/notebook_secret
[W 19:08:25.645 NotebookApp] Notebook pycon-pandas-tutorial/Exercises-1.ipynb is not trusted
[I 19:08:27.843 NotebookApp] Kernel started: d34339cc-4141-49f9-aa53-1ba050f2dc5d
[I 19:10:27.956 NotebookApp] Saving file at /pycon-pandas-tutorial/Exercises-1.ipynb
[W 19:10:27.960 NotebookApp] Saving untrusted notebook pycon-pandas-tutorial/Exercises-1.ipynb

**Comment by dbl001** [comment]
Resolved by menu - /File/Trusted Notebook, and switching to Chrome or Firefox.
The notebook server is creating a security exception.  Chrome and Firefox allowed me to continue.
Safari didn't give a warning ... I just couldn't connect the notebook to the server.

**Comment by brandon-rhodes** [comment]
Interesting! I have never heard of that problem before. Thanks for pasting the error here with a possible solution — hopefully others who encounter the same problem will find the notes you have made here!

**Comment by dbl001** [comment]
Hi Brandon,

I’m still trying to make sense of it …

http://stackoverflow.com/questions/9963621/python-ssl-wrong-version-number http://stackoverflow.com/questions/9963621/python-ssl-wrong-version-number

David-Laxers-MacBook-Pro:~ davidlaxer$ ipython notebook --profile=nbserver
[I 19:08:00.252 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js
[I 19:08:00.317 NotebookApp] Serving notebooks from local directory: /Users/davidlaxer
[I 19:08:00.317 NotebookApp] 0 active kernels 
[I 19:08:00.317 NotebookApp] The IPython Notebook is running at: https://127.0.0.1:9999/
[I 19:08:00.317 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 19:08:25.637 NotebookApp] Writing notebook-signing key to /Users/davidlaxer/.ipython/profile_nbserver/security/notebook_secret
[W 19:08:25.645 NotebookApp] Notebook pycon-pandas-tutorial/Exercises-1.ipynb is not trusted
[I 19:08:27.843 NotebookApp] Kernel started: d34339cc-4141-49f9-aa53-1ba050f2dc5d
[I 19:10:27.956 NotebookApp] Saving file at /pycon-pandas-tutorial/Exercises-1.ipynb
[W 19:10:27.960 NotebookApp] Saving untrusted notebook pycon-pandas-tutorial/Exercises-1.ipynb
[I 22:02:42.201 NotebookApp] Saving file at /pycon-pandas-tutorial/Exercises-1.ipynb
[I 22:04:45.950 NotebookApp] Saving file at /pycon-pandas-tutorial/Exercises-1.ipynb

[W 22:08:36.100 NotebookApp] Notebook pycon-pandas-tutorial/Exercises-2.ipynb is not trusted
[I 22:08:37.503 NotebookApp] Kernel started: fb7d4b59-fcf4-4cfe-8190-739ef1928337
[I 22:08:43.914 NotebookApp] Saving file at /pycon-pandas-tutorial/Exercises-2.ipynb
[I 22:17:20.994 NotebookApp] Using existing profile dir: u'/Users/davidlaxer/.ipython/profile_nbserver'
[I 22:17:29.264 NotebookApp] Using existing profile dir: u'/Users/davidlaxer/.ipython/profile_default'
[I 22:18:03.976 NotebookApp] Kernel shutdown: d34339cc-4141-49f9-aa53-1ba050f2dc5d
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/Users/davidlaxer/anaconda/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/IPython/kernel/zmq/parentpoller.py", line 35, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'getppid'
[I 22:18:05.629 NotebookApp] Kernel shutdown: fb7d4b59-fcf4-4cfe-8190-739ef1928337
[I 22:18:17.514 NotebookApp] Kernel started: e81bf8cd-72ea-40e1-87e8-330cd884ff90
[I 22:23:04.151 NotebookApp] Saving file at /pycon-pandas-tutorial/Exercises-1.ipynb
[W 22:23:12.272 NotebookApp] Notebook pydata-book/ch02.ipynb is not trusted
[I 22:23:18.682 NotebookApp] Kernel started: 82d56f4e-a231-4553-843c-321d3673a5f9
[I 22:23:53.647 NotebookApp] Saving file at /pydata-book/ch02.ipynb
[I 22:26:00.713 NotebookApp] Saving file at /pydata-book/ch02.ipynb
[I 22:35:37.189 NotebookApp] 302 GET /notebooks/pydata-book/ch02.ipynb (127.0.0.1) 1.48ms
[I 22:35:43.163 NotebookApp] 302 POST /login?next=%2Fnotebooks%2Fpydata-book%2Fch02.ipynb (127.0.0.1) 1.14ms
[W 22:36:55.811 NotebookApp] SSL Error on 50 ('127.0.0.1', 60661): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 22:36:55.812 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(_exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 22:36:55.815 NotebookApp] SSL Error on 50 ('127.0.0.1', 60662): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 22:36:55.815 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(_exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 22:36:55.821 NotebookApp] SSL Error on 50 ('127.0.0.1', 60663): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 22:36:55.822 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(_exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 22:36:55.846 NotebookApp] SSL Error on 50 ('127.0.0.1', 60664): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 22:36:55.848 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(_exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 22:36:55.859 NotebookApp] SSL Error on 50 ('127.0.0.1', 60665): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 22:36:55.875 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(_exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 22:36:55.876 NotebookApp] SSL Error on 50 ('127.0.0.1', 60666): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 22:36:55.877 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(_exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[I 22:37:48.686 NotebookApp] Saving file at /pydata-book/ch02.ipynb
[W 00:55:23.190 NotebookApp] error on read
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/iostream.py", line 644, in _handle_read
        pos = self._read_to_buffer_loop()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/iostream.py", line 614, in _read_to_buffer_loop
        if self._read_to_buffer() == 0:
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/iostream.py", line 726, in _read_to_buffer
        chunk = self.read_from_fd()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/iostream.py", line 1419, in read_from_fd
        chunk = self.socket.read(self.read_chunk_size)
      File "/Users/davidlaxer/anaconda/lib/python2.7/ssl.py", line 621, in read
        v = self._sslobj.read(len or 1024)
    SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1752)
[E 00:55:23.224 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(_exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1752)
[I 00:55:41.421 NotebookApp] 302 GET /notebooks/pydata-book/ch02.ipynb (127.0.0.1) 4.10ms
[I 00:55:47.229 NotebookApp] 302 POST /login?next=%2Fnotebooks%2Fpydata-book%2Fch02.ipynb (127.0.0.1) 1.99ms
[I 00:56:44.181 NotebookApp] Saving file at /pydata-book/ch02.ipynb
[W 08:22:47.934 NotebookApp] SSL Error on 6 ('127.0.0.1', 56430): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 08:22:47.942 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(_exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 08:22:47.956 NotebookApp] SSL Error on 6 ('127.0.0.1', 56431): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 08:22:47.957 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(_exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[W 08:22:47.963 NotebookApp] SSL Error on 6 ('127.0.0.1', 56432): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
[E 08:22:47.963 NotebookApp] Uncaught exception
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 693, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(_exc_info)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/http1connection.py", line 168, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)

**Comment by dbl001** [comment]
FYI

https://github.com/ipython/ipython/issues/8621#issuecomment-120142306 https://github.com/ipython/ipython/issues/8621#issuecomment-120142306
